config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "events#index"
  resources :events
  resources :users, only: [:index, :show]
  resources :event_attendees, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
    belongs_to :creator, class_name: "User"
    #this line establishes how an event can have many attendees (Users) with the through table EventAttendee
    #source is saying "find the attendee in EventAttendee with :event_attendee_id, not user_id or w/e"
    has_many :attendees, through: :event_attendees, source: :event_attendee
    #this line establishes how it can have many instances of EventAttendee
    has_many :event_attendees, foreign_key: :attended_event_id, dependent: :delete_all

    scope :past, -> { where('date < ?', Time.now) }
    scope :upcoming, -> { where('date > ?', Time.now) }
 
    validates :creator_id, presence: true
    validates :title, presence: true, length: { in: 1..50}
    validates :location, presence: true, length: { in:  1..100}
    validates_date :date
end

app/models/event_attendee.rb
class EventAttendee < ApplicationRecord
    belongs_to :attended_event, class_name: "Event"
    belongs_to :event_attendee, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  #one-to-many
  has_many :events, foreign_key: :creator_id, class_name: "Event", dependent: :delete_all
  #many-to-many attendees with events, using a through table called event_attendees
  #this line establishes what the foregin key for an attendee is in the event_attendees through table
  has_many :event_attendees, foreign_key: :event_attendee_id
  #hopefully we're not accidently deleting all events that were attended, and just this user's sign up, snrk
  has_many :attended_events, through: :event_attendees, source: :attended_event, dependent: :delete_all

  validates :username, presence: true, length: { minimum: 2 }, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_paramters, if: :devise_controller?
    
    protected

    def configure_permitted_paramters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    end
end

app/controllers/event_attendees_controller.rb
class EventAttendeesController < ApplicationController
    def create
        #:event_id is passed from the link_to inside views/events/show.html.erb
        @event = Event.find(params[:event_id])
        @event_attendee = EventAttendee.new(event_attendee_id: current_user.id, attended_event_id: @event.id)

        #Prevent users from signing up for the same event multiple times
        if EventAttendee.exists?(event_attendee_id: current_user.id, attended_event_id: @event.id)
            redirect_to @event, notice: "You're already attending this event!"
        else
            @event_attendee.save
            redirect_to @event, notice: "You are now attending this event!"
        end
    end

    def destroy
        @event = Event.find(params[:event_id])
        @event_attendee = EventAttendee.find_by(event_attendee_id: current_user.id, attended_event_id: @event.id)
        @event_attendee.destroy

        redirect_to @event, notice: "You have left this event"
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
    before_action :authenticate_user!, except: [:index, :show]

    def index
        @events = Event.all
    end

    def show
        @event = Event.find(params[:id])
        @event_attendees = EventAttendee.where(attended_event_id: @event.id)
    end

    def new
        @event = current_user.events.build
    end

    def create
        @event = current_user.events.build(event_params)

        if @event.save
            redirect_to @event
        else
            render :new
        end
    end

    def edit
        @event = Event.find(params[:id])
        if current_user.id != @event.creator_id
            #surely there is a better way
            redirect_to @event, notice: "You can't do that! 3:"
        end
    end

    def update
        @event = Event.find(params[:id])

        if @event.update(event_params)
            redirect_to @event
        else
            render :edit
        end
    end

    def destroy
        @event = Event.find(params[:id])
        @event.destroy

        redirect_to root_path
    end
    
    private

    def event_params
        params.require(:event).permit(:title, :location, :date, :description)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    
    def index
        @users = User.all
    end
    
    def show
        @user = User.find(params[:id])
        @events_attended = EventAttendee.where(event_attendee_id: @user.id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_attendees_helper.rb
module EventAttendeesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_form.html.erb
<%= form_with model: event do |form| %>
    <%= form.label :title %><br />
    <%= form.text_field :title %><br /><br />
    <% event.errors.full_messages_for(:title).each do |message| %>
        <div><%= message %></div>
    <% end %>

    <%= form.label :location %><br />
    <%= form.text_field :location %><br /><br />
    <% event.errors.full_messages_for(:location).each do |message| %>
        <div><%= message %></div>
    <% end %>

    <%= form.label :date %><br />
    <%= form.text_field :date, placeholder: "dd/mm/yyyy hh:mm" %><br /><br />
    <% event.errors.full_messages_for(:date).each do |message| %>
        <div><%= message %></div>
    <% end %>

    <%= form.label :description %><br />
    <%= form.text_area :description, placeholder: "Tell us a bit about your event." %><br /><br />

    <%= form.submit "Submit" %>
<% end %>

app/views/events/edit.html.erb
<h1>Edit your Event</h1>

<%= render "form", event: @event %>

<%= link_to "Back", :back %>

app/views/events/index.html.erb
<h1>Private Events</h1>

<% if user_signed_in? %>
    <%= link_to "New Event", new_event_path%>
<% end %>

<hr>

<h4>Upcoming Events</h4>
<ul>
    <% Event.upcoming.each do |event| %>
        <li><%= link_to "#{event.title}", event %></li>
    <% end %>
</ul>

<hr>

<h4>Past Events</h4>
<ul>
    <% Event.past.each do |event| %>
        <li><%= link_to "#{event.title}", event %></li>
    <% end %>
</ul>

app/views/events/new.html.erb
<h1>New Event</h1>
<p>Please fill out the information for your event below</p>

<%= render 'form', event: @event%>

<%= link_to "Back", root_path %>

app/views/events/show.html.erb
<h1><%= @event.title %></h1>
<h4>Creator: <%= link_to "#{@event.creator.username}", user_path(@event.creator) %></h4>

<p>Time: <%= @event.date %></p>
<p>Place: <%= @event.location %></p>
<p><%= @event.description %></p>

<!-- Show one button or the other depending on if they're already attending the event -->
<% if user_signed_in? %>
    <% if EventAttendee.exists?(event_attendee_id: current_user.id, event_attendee_id: @event.id) %>
        <%= link_to "Unattend", event_attendee_path(event_id: @event.id),
                                                method: :delete,
                                                data: { confirm: "You want to leave this event?" } %>
    <% else %>
        <%= link_to "Attend", event_attendees_path(event_id: @event.id),
                                                method: :post,
                                                data: { confirm: "Do you want to attend this event?" } %>
    <% end %>
    <% if current_user.id == @event.creator_id %>
        <%= link_to "Edit", edit_event_path(@event) %>
        <%= link_to "Delete", event_path(@event), 
                                method: :delete, 
                                data: { confirm: "You're really sure you want to delete your event?" } %>
    <% end %>
<% end %>
<%= link_to "Back", root_path %>

<hr>

<p>Attendees:</p>
<ul>
    <% @event_attendees.each do |ea| %>
        <% attendee = User.find(ea.event_attendee_id) %>
        <li><%= link_to "#{attendee.username}", attendee %></li>
    <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!-- devise flash message defaults -->
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <!-- Nav bar -->
    <% if user_signed_in? %>
      <%= link_to "#{current_user.username}", user_path(current_user) %>
      (<%= link_to "Sign Out", destroy_user_session_path, 
                            method: :delete, 
                            data: { confirm: "Sign out?" } %>)
    <% else %>
      <%= link_to "Sign In", new_user_session_path %> |
      <%= link_to "Sign Up", new_user_registration_path %>
    <% end %>
    <%= link_to "Home", root_path %>
    <%= link_to "Users", users_path %>

    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<h1>User List</h1>

<% @users.each do |user| %>
    <%= link_to "#{user.username}", user %><br>
<% end %>

app/views/users/show.html.erb
<h3><%= @user.username %>'s Profile </h3>

<h5>Hosting:</h5>
<ul>
    <% if @user.events.size == 0 %>
        <p>This user has no events.</p>
    <% else %>
        <% @user.events.each do |event| %>
            <li><%= link_to "#{event.title}", event %></li>
        <% end %>
    <% end %>
</ul>

<hr>


<h6>Attending upcoming events:</h6>
<ul>
    <!-- You can use queries instead of relying on if-statements! -->
    <% @user.attended_events.where('date > ?', Time.now).each do |event| %>
        <li><%= link_to "#{event.title}", event %></li>
    <% end %>
</ul>

<hr>

<h6>Past Events Attended:</h6>
<ul>
    <% @user.attended_events.where('date < ?', Time.now).each do |event| %>
        <li><%= link_to "#{event.title}", event %></li>
    <% end %>
</ul>

<%= link_to "Back", root_path %>